[package]
name = "buddhabrot"
version = "0.1.0"
authors = ["Adam Vandenbussche <adam@avdb.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.15.2"